#!/usr/bin/env python3
"""Put one navigation bar on every page of poidhz.com, and keep it identical.

WHY, MEASURED 2026-09-22 by reading the topnav out of each page on disk:

    index.html                   poidhz | calendar | dashboard | best practices | rounds | repo | poidh
    docs/about.html              poidhz | repo | calendar | best practices | leaderboard json | bcz
    docs/poidh-hub.html          BetterCallZaal | Nexus | $ZABAL Empire | POIDH album | Home
    docs/lost.html               poidhz | calendar | leaderboard | about | best practices | repo
    docs/bounty-best-practices   BetterCallZaal | Nexus | POIDH Hub | R2 Judging | ZABAL Gamez
    docs/bounty-dashboard.html   NO TOPNAV
    docs/create-bounty.html      NO TOPNAV
    docs/bounty-calendar.html    NO TOPNAV

Eight pages, six different navigations, three with no way out at all. A visitor who lands on
the dashboard is at a dead end, and nothing anywhere linked to /feedback.

HOW IT AVOIDS BREAKING THE PAGES IT EDITS. The bar is written between sentinels and carries its
own scoped styles under `.zn-*` class names, so it never depends on a page's own CSS and never
collides with it. Re-running replaces what is between the sentinels, so this is idempotent and
a nav change is one edit here rather than eight by hand. STRIPPING THE OLD BARS. The first version of this left each page's own `.topnav` in place,
reasoning that those bars carried page-specific links and removing them would be a guess about
someone else's design. On the live site that produced TWO stacked navigation bars on every
page, which is worse than the drift it replaced. Zaal, 2026-09-22, looking at it: "clean this
up". So the old `.topnav` is now removed, and the handful of destinations that were ONLY
reachable from one of those bars were checked link by link first and either added to the
canonical bar (/hub) or moved into that page's footer (bettercallzaal.com, Nexus, R2 judging,
ZABAL Gamez). Nothing was dropped silently.

    python3 scripts/sync-site-nav.py
    python3 scripts/sync-site-nav.py --check
    python3 scripts/sync-site-nav.py --selftest
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
START = "<!-- ZN-NAV START - generated by scripts/sync-site-nav.py, do not hand-edit -->"
END = "<!-- ZN-NAV END -->"

# label, href. Order is the order a visitor most likely needs it.
LINKS = [
    ("calendar", "/"),
    ("dashboard", "/dashboard"),
    ("rounds", "/about"),
    ("feedback", "/feedback"),
    ("the bar", "/best-practices"),
    ("hub", "/hub"),
    ("leaderboard", "/leaderboard"),
    ("create a bounty", "/create-bounty"),
]

PAGES = [
    "index.html",
    "docs/about.html",
    "docs/lost.html",
    "docs/poidh-hub.html",
    "docs/bounty-dashboard.html",
    "docs/bounty-calendar.html",
    "docs/create-bounty.html",
    "docs/bounty-best-practices.html",
]

NAV_CSS = """<style>
.zn-nav{background:#0b0b0f;border-bottom:1px solid #1f1e26;font-family:'Outfit',system-ui,sans-serif;
position:relative;z-index:50}
.zn-nav-in{max-width:1100px;margin:0 auto;padding:.7rem 1.5rem;display:flex;align-items:center;
gap:1.1rem;flex-wrap:wrap}
.zn-brand{font-family:'Syne','Outfit',system-ui,sans-serif;font-weight:800;font-size:1rem;
color:#e4e2dd;text-decoration:none;margin-right:.25rem}
.zn-brand:hover{color:#ff6b35}
.zn-nav a.zn-l{color:#8a8895;text-decoration:none;font-size:.88rem;transition:color .15s}
.zn-nav a.zn-l:hover{color:#00e5ff}
.zn-nav a.zn-l[aria-current=page]{color:#f5c842}
.zn-spacer{margin-left:auto}
@media(max-width:640px){.zn-nav-in{gap:.8rem;padding:.6rem 1rem}.zn-nav a.zn-l{font-size:.82rem}}
</style>"""


def nav_html(here: str) -> str:
    out = [START, NAV_CSS, '<div class="zn-nav"><div class="zn-nav-in">',
           '<a class="zn-brand" href="/">poidhz</a>']
    for label, href in LINKS:
        cur = ' aria-current="page"' if href == here else ""
        out.append(f'<a class="zn-l" href="{href}"{cur}>{label}</a>')
    out.append('<a class="zn-l zn-spacer" href="https://github.com/bettercallzaal/poidhz">repo</a>')
    out.append('<a class="zn-l" href="https://poidh.xyz">poidh</a>')
    out.append("</div></div>")
    out.append(END)
    return "\n".join(out)


# Which nav entry each page IS, so it can mark itself current. A page not listed simply has no
# current item, which is correct rather than wrong.
SELF = {
    "index.html": "/",
    "docs/about.html": "/about",
    "docs/bounty-dashboard.html": "/dashboard",
    "docs/bounty-best-practices.html": "/best-practices",
    "docs/create-bounty.html": "/create-bounty",
}


def apply(text: str, here: str) -> str:
    block = nav_html(here)
    if START in text and END in text:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text,
                      flags=re.S)
    m = re.search(r"<body[^>]*>", text)
    if not m:
        raise ValueError("no <body> tag, so there is nowhere to put a nav")
    return text[:m.end()] + "\n" + block + "\n" + text[m.end():]


def run(check: bool = False) -> tuple[bool, list[str]]:
    findings: list[str] = []
    changed = 0
    # The generated feedback pages get the same bar. They are rebuilt by
    # build-feedback-pages.py, so this must run AFTER that script, and --check in CI is what
    # catches a rebuild that dropped the nav.
    pages = list(PAGES) + sorted(
        str(p.relative_to(REPO_ROOT))
        for p in (REPO_ROOT / "feedback").rglob("*.html"))
    missing = [p for p in PAGES if not (REPO_ROOT / p).exists()]
    if missing:
        return False, [f"FAIL: these pages are listed but not on disk: {missing}. "
                       f"The list is stale, which means some page is going unnavigated."]

    for rel in pages:
        p = REPO_ROOT / rel
        src = p.read_text()
        try:
            out = apply(src, SELF.get(rel, ""))
        except ValueError as e:
            return False, [f"FAIL: {rel} - {e}"]
        if out != src:
            changed += 1
            if not check:
                p.write_text(out)
            findings.append(f"     {'would update' if check else 'updated'} {rel}")
        else:
            findings.append(f"     {rel} already current")

    findings.append(f"PASS: {len(pages)} page(s) carry the same {len(LINKS) + 2}-link nav, "
                    f"{changed} changed")
    return (not (check and changed)), findings


def _selftest() -> bool:
    passed = True

    def c(label, cond):
        nonlocal passed
        print(f"  {'ok  ' if cond else 'FAIL'} {label}")
        passed = passed and bool(cond)

    page = "<html><head></head><body>\n<div class='container'>hi</div>\n</body></html>"
    once = apply(page, "/")
    c("inserts a nav into a page that had none", START in once and "zn-nav" in once)
    c("keeps the original content", "<div class='container'>hi</div>" in once)
    c("the nav links feedback", 'href="/feedback"' in once)
    c("marks the current page", 'href="/"' in once and 'aria-current="page"' in once)

    twice = apply(once, "/")
    c("is idempotent, not additive", twice.count(START) == 1 and twice == once)

    # A nav change must propagate on re-run rather than being appended alongside the old one.
    LINKS.append(("new thing", "/new"))
    try:
        updated = apply(once, "/")
        c("a changed nav REPLACES the old block", updated.count(START) == 1
          and "/new" in updated)
    finally:
        LINKS.pop()

    reverted = apply(updated, "/")
    c("and reverting the link list takes it back out", "/new" not in reverted)

    try:
        apply("<html><head></head></html>", "/")
        raised = False
    except ValueError:
        raised = True
    c("a page with no <body> is refused, not silently skipped", raised)
    return passed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if any page is out of date")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        print("sync-site-nav selftest")
        ok = _selftest()
        print("selftest:", "passed" if ok else "FAILED")
        return 0 if ok else 1

    ok, findings = run(check=args.check)
    for f in findings:
        print(f"  {f}")
    if args.check and not ok:
        print("\nRun scripts/sync-site-nav.py to bring every page back in line.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
